"""Add html column in blog module

Revision ID: 3a4d710eea29
Revises: e1093a072482
Create Date: 2024-02-05 05:26:47.501466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4d710eea29'
down_revision = 'e1093a072482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blogs', schema=None) as batch_op:
        batch_op.drop_column('post_html')

    # ### end Alembic commands ###
