"""Rename table names

Revision ID: 61b8c9b0ffbe
Revises: dfe09ab38244
Create Date: 2024-02-01 08:51:24.312636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61b8c9b0ffbe'
down_revision = 'dfe09ab38244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['Blogs.post_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('Blog-Comments', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('name')

    op.drop_table('Blog-Comments')
    with op.batch_alter_table('Comments-Replies', schema=None) as batch_op:
        batch_op.drop_constraint('Comments-Replies_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comments-Replies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Comments-Replies_ibfk_1', 'Blog-Comments', ['comment_id'], ['id'])

    op.create_table('Blog-Comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('blog_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['Blogs.post_id'], name='Blog-Comments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Blog-Comments', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.drop_table('comments')
    # ### end Alembic commands ###
