"""Modify blogs model

Revision ID: 6bfc3a758b02
Revises: 3a4d710eea29
Create Date: 2024-02-05 13:05:22.588200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfc3a758b02'
down_revision = '3a4d710eea29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blogs', schema=None) as batch_op:
        batch_op.drop_column('title_html')

    # ### end Alembic commands ###
