"""Add Comments and Tags tables

Revision ID: a88b0615307e
Revises: dc9130c3993e
Create Date: 2024-01-25 10:28:57.678297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a88b0615307e'
down_revision = 'dc9130c3993e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Blog Comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['Blogs.post_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blog tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['Blogs.post_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    with op.batch_alter_table('Blogs', schema=None) as batch_op:
        batch_op.alter_column('post',
               existing_type=mysql.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('date_created',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('date_updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('date_updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('date_created',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('post',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=5000),
               existing_nullable=False)

    op.drop_table('blog tags')
    op.drop_table('Blog Comments')
    op.drop_table('tag')
    # ### end Alembic commands ###
