"""Modify comments model to accomodate markdown

Revision ID: ce1123cf63b9
Revises: 6bfc3a758b02
Create Date: 2024-02-05 14:43:58.677362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1123cf63b9'
down_revision = '6bfc3a758b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blog Comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('disabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blog Comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('disabled')
        batch_op.drop_column('comment_html')

    # ### end Alembic commands ###
