"""Rename table names

Revision ID: dfe09ab38244
Revises: e6c53aad4f3f
Create Date: 2024-02-01 08:19:16.136437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfe09ab38244'
down_revision = 'e6c53aad4f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blog-Comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['Blogs.post_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Comments-Replies',
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['Blog-Comments.id'], ),
    sa.PrimaryKeyConstraint('reply_id')
    )
    op.drop_table('comment_reply')
    with op.batch_alter_table('Blog Comments', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('name')

    op.drop_table('Blog Comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blog Comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('blog_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['Blogs.post_id'], name='Blog Comments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Blog Comments', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('comment_reply',
    sa.Column('reply_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reply', mysql.TEXT(), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('comment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['Blog Comments.id'], name='comment_reply_ibfk_1'),
    sa.PrimaryKeyConstraint('reply_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Comments-Replies')
    op.drop_table('Blog-Comments')
    # ### end Alembic commands ###
