"""Add comment reply model

Revision ID: e6c53aad4f3f
Revises: 66d13efad552
Create Date: 2024-02-01 08:07:15.499935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c53aad4f3f'
down_revision = '66d13efad552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_reply',
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['Blog Comments.id'], ),
    sa.PrimaryKeyConstraint('reply_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_reply')
    # ### end Alembic commands ###
