"""Change Posts column types

Revision ID: fc2709b6d975
Revises: a88b0615307e
Create Date: 2024-01-25 12:55:33.304015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2709b6d975'
down_revision = 'a88b0615307e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blogs', schema=None) as batch_op:
        batch_op.drop_index('ix_Blogs_post_author')
        batch_op.create_index(batch_op.f('ix_Blogs_post_author'), ['post_author'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Blogs_post_author'))
        batch_op.create_index('ix_Blogs_post_author', ['post_author'], unique=True)

    # ### end Alembic commands ###
